"""Add guest fields to orders

Revision ID: 336e981c18a7
Revises: 
Create Date: 2024-09-02 18:25:25.995899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336e981c18a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_constraint('order_products_product_id_fkey', 'order_products', type_='foreignkey')
    op.drop_constraint('order_products_order_id_fkey', 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_products', 'products', ['product_id'], ['id'])
    op.add_column('orders', sa.Column('guest_email', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint('product_categories_product_id_fkey', 'product_categories', type_='foreignkey')
    op.drop_constraint('product_categories_category_id_fkey', 'product_categories', type_='foreignkey')
    op.create_foreign_key(None, 'product_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product_categories', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.create_foreign_key('product_categories_category_id_fkey', 'product_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('product_categories_product_id_fkey', 'product_categories', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_column('orders', 'guest_address')
    op.drop_column('orders', 'guest_email')
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_foreign_key('order_products_order_id_fkey', 'order_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_products_product_id_fkey', 'order_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
