"""baseline

Revision ID: 6f4b0bdf566f
Revises: 
Create Date: 2025-09-16 00:17:49.901015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4b0bdf566f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_visible', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('sold_count', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('last_viewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'last_viewed_at')
    op.drop_column('products', 'sold_count')
    op.drop_column('products', 'view_count')
    op.drop_column('products', 'is_visible')
    # ### end Alembic commands ###
