"""Add binary media storage to ProductMedia

Revision ID: a5694c6e0c31
Revises: c72a44b77f75
Create Date: 2025-05-21 21:53:50.203850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5694c6e0c31'
down_revision: Union[str, None] = 'c72a44b77f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('product_media', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('product_media', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.drop_column('product_media', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('product_media', 'data')
    op.drop_column('product_media', 'content_type')
    op.drop_column('product_media', 'filename')
    # ### end Alembic commands ###
